/*
* generated by Xtext
*/
package net.sf.dftools.cdl.ui.contentassist;

import net.sf.dftools.cdl.ui.contentassist.AbstractCdlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CdlProposalProvider extends AbstractCdlProposalProvider {

}
