
#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "preesm-sonarcloud-org"
    token:
      secure: "7edfa331c5de80bf665aee04f0e9dbcbc3efa122"
    branches: .*

#######################
# Actual build stages
#######################
# The following job can be reproduced on any machine in a single line
# with the following:
#
# mvn -U -e -C -V -P releng clean checkstyle:check package verify -fae
#
# Note that sonar and findbugs are disable since they not proper config.
# The job is separated in several stages to detect quickly where the
# issue is comming from.
#######################

script: timeout 90m ./releng/build_and_test.sh

#skip install step before each stage by running the /bin/true command
install: true
