/*
 * generated by Xtext
 */
package net.sf.dftools.cdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CdlUiModule extends net.sf.dftools.cdl.ui.AbstractCdlUiModule {
	public CdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
