/*
 * generated by Xtext
 */
package net.sf.dftools.cdl.scoping;

import net.sf.dftools.cdl.cdl.Class;
import net.sf.dftools.cdl.cdl.Core;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class CdlScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_Field_attribute(Core core, EReference reference) {
		Class clasz = core.getType();
		return Scopes.scopeFor(clasz.getAttributes());
	}

	public IScope scope_LiteralEnum_value(Core core, EReference reference) {
		Class clasz = core.getType();
		return Scopes.scopeFor(clasz.getAttributes());
	}

}
