/*
* generated by Xtext
*/
package net.sf.dftools.cdl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CdlTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
