/*
 * generated by Xtext
 */
package net.sf.dftools.cdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CdlRuntimeModule extends net.sf.dftools.cdl.AbstractCdlRuntimeModule {

}
